# Generated by Django 6.0.6 on 2026-07-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(blank=True, verbose_name="ポスター画像URL"),
        ),
        migrations.AddField(
            model_name="movie",
            name="tmdb_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="TMDB映画ID"
            ),
        ),
    ]
