# Generated by Django 6.0.6 on 2026-07-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_poster_url_movie_tmdb_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="sentiment",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
